# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/main.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import Qt
from PyQt5.QtWidgets import QApplication

class Ui_MainWindow(object):
    QApplication.setAttribute(Qt.AA_EnableHighDpiScaling)
    QApplication.setAttribute(Qt.AA_UseHighDpiPixmaps)
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(842, 465)
        MainWindow.setMaximumSize(842, 465)
        MainWindow.setMinimumSize(842, 465)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons_2/icons/dollar@High.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet("QMainWindow{\n"
"    background-color:#EDE8F5;\n"
"}\n"
"QMenuBar{\n"
"    background:rgb(0, 85, 127);\n"
"    color:white;\n"
"}\n"
"\n"
"QMenu{\n"
"    background:rgb(0, 85, 127);\n"
"    color:white;\n"
"}\n"
"QMenu:hover{\n"
"    background-color:white;\n"
"    color:black;\n"
"}\n"
"QAction:hover{\n"
"    background-color:white;\n"
"    color:black;\n"
"}    \n"
"\n"
"")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.sidenav_icons_2 = QtWidgets.QWidget(self.centralwidget)
        self.sidenav_icons_2.setGeometry(QtCore.QRect(10, 50, 161, 391))
        self.sidenav_icons_2.setStyleSheet("QWidget{\n"
"     \n"
"    background-color: rgb(173, 136, 218);\n"
"    border-radius:5px;\n"
"}")
        self.sidenav_icons_2.setObjectName("sidenav_icons_2")
        self.label_2 = QtWidgets.QLabel(self.sidenav_icons_2)
        self.label_2.setGeometry(QtCore.QRect(40, 10, 21, 21))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap(":/icons/png_64/Coin-Dollar.png"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.sidenav_icons_2)
        self.label_3.setGeometry(QtCore.QRect(80, 10, 51, 16))
        font = QtGui.QFont()
        font.setFamily("calibri")
        font.setPointSize(12)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color:white;\n"
"font-family:calibri;\n"
"font-size:12pt;")
        self.label_3.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.label_3.setObjectName("label_3")
        self.layoutWidget = QtWidgets.QWidget(self.sidenav_icons_2)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 60, 159, 291))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.income_tracking_btn = QtWidgets.QPushButton(self.layoutWidget)
        self.income_tracking_btn.setStyleSheet("QPushButton{\n"
"    border:none;\n"
"    border-radius:8px;\n"
"    background:rgb(255, 255, 255);\n"
"    transition: background-color 0.25;\n"
"    font-family:Calibri;\n"
"    font-size:10pt;\n"
"    color:rgb(255, 85, 0);\n"
"    text-align:left;\n"
"    padding-left:10px;\n"
"    \n"
"}\n"
"QPushButton:hover{\n"
"    background:rgb(170, 255, 255);\n"
"    color:rgb(55, 102, 127);\n"
"}")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/png_64/Money-Slot.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.income_tracking_btn.setIcon(icon1)
        self.income_tracking_btn.setIconSize(QtCore.QSize(20, 30))
        self.income_tracking_btn.setCheckable(True)
        self.income_tracking_btn.setAutoExclusive(True)
        self.income_tracking_btn.setObjectName("income_tracking_btn")
        self.verticalLayout.addWidget(self.income_tracking_btn)
        self.expence_tracking_btn = QtWidgets.QPushButton(self.layoutWidget)
        self.expence_tracking_btn.setStyleSheet("QPushButton{\n"
"    border:none;\n"
"    border-radius:8px;\n"
"    background:rgb(255, 255, 255);\n"
"    transition: background-color 0.25;\n"
"    font-family:Calibri;\n"
"    font-size:10pt;\n"
"    color:rgb(255, 85, 0);\n"
"    text-align:left;\n"
"    padding-left:10px;\n"
"    \n"
"}\n"
"QPushButton:hover{\n"
"    background:rgb(170, 255, 255);\n"
"    color:rgb(55, 102, 127);\n"
"}")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/png_64/Chart.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.expence_tracking_btn.setIcon(icon2)
        self.expence_tracking_btn.setIconSize(QtCore.QSize(20, 30))
        self.expence_tracking_btn.setCheckable(True)
        self.expence_tracking_btn.setAutoExclusive(True)
        self.expence_tracking_btn.setObjectName("expence_tracking_btn")
        self.verticalLayout.addWidget(self.expence_tracking_btn)
        self.budget_management_btn = QtWidgets.QPushButton(self.layoutWidget)
        self.budget_management_btn.setStyleSheet("QPushButton{\n"
"    border:none;\n"
"    border-radius:8px;\n"
"    background:rgb(255, 255, 255);\n"
"    transition: background-color 0.25;\n"
"    font-family:Calibri;\n"
"    font-size:10pt;\n"
"    color:rgb(255, 85, 0);\n"
"    text-align:left;\n"
"    padding-left:10px;\n"
"    \n"
"}\n"
"QPushButton:hover{\n"
"    background:rgb(170, 255, 255);\n"
"    color:rgb(55, 102, 127);\n"
"}")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icons/png_64/Bill.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.budget_management_btn.setIcon(icon3)
        self.budget_management_btn.setIconSize(QtCore.QSize(20, 30))
        self.budget_management_btn.setCheckable(True)
        self.budget_management_btn.setAutoExclusive(True)
        self.budget_management_btn.setObjectName("budget_management_btn")
        self.verticalLayout.addWidget(self.budget_management_btn)
        self.reports_btn = QtWidgets.QPushButton(self.layoutWidget)
        self.reports_btn.setStyleSheet("QPushButton{\n"
"    border:none;\n"
"    border-radius:8px;\n"
"    background:rgb(255, 255, 255);\n"
"    transition: background-color 0.25;\n"
"    font-family:Calibri;\n"
"    font-size:10pt;\n"
"    color:rgb(255, 85, 0);\n"
"    text-align:left;\n"
"    padding-left:10px;\n"
"    \n"
"}\n"
"QPushButton:hover{\n"
"    background:rgb(170, 255, 255);\n"
"    color:rgb(55, 102, 127);\n"
"}")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/icons/png_64/Presentation-.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.reports_btn.setIcon(icon4)
        self.reports_btn.setIconSize(QtCore.QSize(20, 30))
        self.reports_btn.setCheckable(True)
        self.reports_btn.setAutoExclusive(True)
        self.reports_btn.setObjectName("reports_btn")
        self.verticalLayout.addWidget(self.reports_btn)
        self.quit_btn = QtWidgets.QPushButton(self.layoutWidget)
        self.quit_btn.setStyleSheet("QPushButton{\n"
"    border:none;\n"
"    border-radius:8px;\n"
"    background:rgb(255, 255, 255);\n"
"    transition: background-color 0.25;\n"
"    font-family:Calibri;\n"
"    font-size:10pt;\n"
"    color:rgb(255, 85, 0);\n"
"    text-align:left;\n"
"    padding-left:10px;\n"
"    \n"
"}\n"
"QPushButton:hover{\n"
"    background:rgb(255, 155, 155);\n"
"    color:white;\n"
"}")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/icons/png_64/Remove.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.quit_btn.setIcon(icon5)
        self.quit_btn.setIconSize(QtCore.QSize(20, 30))
        self.quit_btn.setObjectName("quit_btn")
        self.verticalLayout.addWidget(self.quit_btn)
        self.menu_bar = QtWidgets.QWidget(self.centralwidget)
        self.menu_bar.setGeometry(QtCore.QRect(0, 0, 851, 41))
        self.menu_bar.setStyleSheet("QWidget{\n"
"    \n"
"    background-color:#7091E6;\n"
"}")
        self.menu_bar.setObjectName("menu_bar")
        self.new_2 = QtWidgets.QPushButton(self.menu_bar)
        self.new_2.setGeometry(QtCore.QRect(10, 0, 41, 41))
        self.new_2.setStyleSheet("QPushButton{\n"
"    border:none;\n"
"    background:white;\n"
"    border-radius:10px;\n"
"}\n"
"QPushButton:hover{\n"
"    background:rgb(237, 237, 237);\n"
"}")
        self.new_2.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/icons/png_64/Plus.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.new_2.setIcon(icon6)
        self.new_2.setIconSize(QtCore.QSize(30, 20))
        self.new_2.setObjectName("new_2")
        self.open = QtWidgets.QPushButton(self.menu_bar)
        self.open.setGeometry(QtCore.QRect(60, 0, 41, 41))
        self.open.setStyleSheet("QPushButton{\n"
"    border:none;\n"
"    background:white;\n"
"    border-radius:10px;\n"
"}\n"
"QPushButton:hover{\n"
"    background:rgb(237, 237, 237);\n"
"}")
        self.open.setText("")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/icons_2/icons/Folder-File.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.open.setIcon(icon7)
        self.open.setIconSize(QtCore.QSize(30, 20))
        self.open.setObjectName("open")
        self.save = QtWidgets.QPushButton(self.menu_bar)
        self.save.setGeometry(QtCore.QRect(110, 0, 41, 41))
        self.save.setStyleSheet("QPushButton{\n"
"    border:none;\n"
"    background:white;\n"
"    border-radius:10px;\n"
"}\n"
"QPushButton:hover{\n"
"    background:rgb(237, 237, 237);\n"
"}")
        self.save.setText("")
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/icons_2/icons/Folder-Checked.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.save.setIcon(icon8)
        self.save.setIconSize(QtCore.QSize(30, 20))
        self.save.setObjectName("save")
        self.label_5 = QtWidgets.QLabel(self.menu_bar)
        self.label_5.setGeometry(QtCore.QRect(260, 5, 581, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(22)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("color:white;")
        self.label_5.setObjectName("label_5")
        self.save_2 = QtWidgets.QPushButton(self.menu_bar)
        self.save_2.setGeometry(QtCore.QRect(160, 0, 41, 41))
        self.save_2.setStyleSheet("QPushButton{\n"
"    border:none;\n"
"    background:white;\n"
"    border-radius:10px;\n"
"}\n"
"QPushButton:hover{\n"
"    background:rgb(237, 237, 237);\n"
"}")
        self.save_2.setText("")
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(":/icons_2/icons/internation-target@High.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.save_2.setIcon(icon9)
        self.save_2.setIconSize(QtCore.QSize(30, 20))
        self.save_2.setObjectName("save_2")
        self.save_3 = QtWidgets.QPushButton(self.menu_bar)
        self.save_3.setGeometry(QtCore.QRect(210, 0, 41, 41))
        self.save_3.setStyleSheet("QPushButton{\n"
"    border:none;\n"
"    background:white;\n"
"    border-radius:10px;\n"
"}\n"
"QPushButton:hover{\n"
"    background:rgb(237, 237, 237);\n"
"}")
        self.save_3.setText("")
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(":/icons_2/icons/mail-outbox@High.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.save_3.setIcon(icon10)
        self.save_3.setIconSize(QtCore.QSize(30, 20))
        self.save_3.setObjectName("save_3")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(180, 50, 611, 381))
        self.widget.setObjectName("widget")
        self.header = QtWidgets.QWidget(self.widget)
        self.header.setGeometry(QtCore.QRect(0, 0, 611, 61))
        self.header.setObjectName("header")
        self.StackedWidget = QtWidgets.QStackedWidget(self.widget)
        self.StackedWidget.setGeometry(QtCore.QRect(70, 20, 531, 351))
        self.StackedWidget.setStyleSheet("border:1px solid black;\n"
"border-radius:10px;")
        self.StackedWidget.setObjectName("StackedWidget")
        self.welcome = QtWidgets.QWidget()
        self.welcome.setObjectName("welcome")
        self.label_19 = QtWidgets.QLabel(self.welcome)
        self.label_19.setGeometry(QtCore.QRect(210, 20, 141, 41))
        self.label_19.setStyleSheet("font: 75 14pt \"Calibri\";\n"
"padding:10px;")
        self.label_19.setObjectName("label_19")
        self.textBrowser = QtWidgets.QTextBrowser(self.welcome)
        self.textBrowser.setGeometry(QtCore.QRect(30, 110, 461, 211))
        self.textBrowser.setObjectName("textBrowser")
        self.StackedWidget.addWidget(self.welcome)
        self.income_tracking_2 = QtWidgets.QWidget()
        self.income_tracking_2.setObjectName("income_tracking_2")
        self.income_source = QtWidgets.QLineEdit(self.income_tracking_2)
        self.income_source.setGeometry(QtCore.QRect(40, 90, 201, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(13)
        self.income_source.setFont(font)
        self.income_source.setObjectName("income_source")
        self.label_6 = QtWidgets.QLabel(self.income_tracking_2)
        self.label_6.setGeometry(QtCore.QRect(50, 70, 191, 16))
        self.label_6.setStyleSheet("border:none;\n"
"font: 10pt \"Calibri\";")
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.income_tracking_2)
        self.label_7.setGeometry(QtCore.QRect(290, 70, 71, 16))
        self.label_7.setStyleSheet("border:none;\n"
"font: 10pt \"Calibri\";")
        self.label_7.setObjectName("label_7")
        self.amount_income = QtWidgets.QLineEdit(self.income_tracking_2)
        self.amount_income.setGeometry(QtCore.QRect(280, 90, 201, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(13)
        self.amount_income.setFont(font)
        self.amount_income.setObjectName("amount_income")
        self.label_8 = QtWidgets.QLabel(self.income_tracking_2)
        self.label_8.setGeometry(QtCore.QRect(50, 140, 71, 16))
        self.label_8.setStyleSheet("border:none;\n"
"font: 10pt \"Calibri\";")
        self.label_8.setObjectName("label_8")
        self.date_income = QtWidgets.QDateEdit(self.income_tracking_2)
        self.date_income.setGeometry(QtCore.QRect(40, 160, 181, 31))
        self.date_income.setStyleSheet("font: 10pt \"Calibri\";\n"
"padding:10px;\n"
"background:white;\n"
"color:black;")
        self.date_income.setWrapping(False)
        self.date_income.setButtonSymbols(QtWidgets.QAbstractSpinBox.UpDownArrows)
        self.date_income.setDateTime(QtCore.QDateTime(QtCore.QDate.currentDate(), QtCore.QTime.currentTime()))
        self.date_income.setMaximumDateTime(QtCore.QDateTime(QtCore.QDate.currentDate(), QtCore.QTime(23, 59, 59)))
        self.date_income.setMinimumDate(QtCore.QDate.currentDate().addYears(-5))
        self.date_income.setCalendarPopup(True)
        self.date_income.setObjectName("date_income")
        self.post_income = QtWidgets.QPushButton(self.income_tracking_2)
        self.post_income.setCheckable(True)
        self.post_income.setGeometry(QtCore.QRect(60, 220, 111, 51))
        self.post_income.setStyleSheet("QPushButton{\n"
"    background:rgb(85, 255, 0);\n"
"    color:rgb(47, 47, 47);\n"
"    border:0.1px solid;\n"
"    font: 87 10pt \"Arial Black\";\n"
"}\n"
"QPushButton:hover{\n"
"    background:rgb(150, 254, 94);\n"
"}")
        self.post_income.setObjectName("post_income")
        self.clear_income = QtWidgets.QPushButton(self.income_tracking_2)
        self.clear_income.setGeometry(QtCore.QRect(350, 220, 111, 51))
        self.clear_income.setStyleSheet("QPushButton{\n"
"    background:rgb(255, 170, 0);\n"
"    color:rgb(47, 47, 47);\n"
"    border:0.1px solid;\n"
"    font: 87 10pt \"Arial Black\";\n"
"}\n"
"QPushButton:hover{\n"
"    background:rgb(255, 205, 105);\n"
"}")
        self.clear_income.setObjectName("clear_income")
        self.label_10 = QtWidgets.QLabel(self.income_tracking_2)
        self.label_10.setGeometry(QtCore.QRect(130, 10, 191, 41))
        self.label_10.setStyleSheet("font: 75 14pt \"Calibri\";\n"
"padding:10px;")
        self.label_10.setObjectName("label_10")
        self.label_21 = QtWidgets.QLabel(self.income_tracking_2)
        self.label_21.setGeometry(QtCore.QRect(130, 50, 401, 16))
        self.label_21.setStyleSheet("border:none;\n"
"font: 10pt \"Calibri\";")
        self.label_21.setObjectName("label_21")
        self.next_income = QtWidgets.QPushButton(self.income_tracking_2)
        self.next_income.setGeometry(QtCore.QRect(350, 150, 111, 51))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(10)
        self.next_income.setFont(font)
        self.next_income.setStyleSheet("QPushButton{\n"
"    background:rgb(24, 64, 62);\n"
"    border:0.1px solid;\n"
"    font: 87 10pt \"Arial Black\";\n"
"}\n"
"QPushButton:hover{\n"
"    background:rgb(255,255,255);\n"
"}")
        self.next_income.setText("")
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap(":/icons_2/icons/2x_arw-rd-right.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.next_income.setIcon(icon11)
        self.next_income.setIconSize(QtCore.QSize(20, 20))
        self.next_income.setObjectName("next_income")
        self.StackedWidget.addWidget(self.income_tracking_2)
        self.expence_tracking = QtWidgets.QWidget()
        self.expence_tracking.setObjectName("expence_tracking")
        self.label_11 = QtWidgets.QLabel(self.expence_tracking)
        self.label_11.setGeometry(QtCore.QRect(130, 10, 181, 41))
        self.label_11.setStyleSheet("font: 75 14pt \"Calibri\";\n"
"padding:10px;")
        self.label_11.setObjectName("label_11")
        self.rent_expence = QtWidgets.QComboBox(self.expence_tracking)
        self.rent_expence.setGeometry(QtCore.QRect(30, 100, 181, 31))
        self.rent_expence.setStyleSheet("font: 10pt \"Calibri\";")
        self.rent_expence.setObjectName("rent_expence")
        self.rent_expence.addItem("")
        self.rent_expence.addItem("")
        self.rent_expence.addItem("")
        self.rent_expence.addItem("")
        self.rent_expence.addItem("")
        self.rent_expence.addItem("")
        self.rent_expence.addItem("")
        self.rent_expence.addItem("")
        self.label_12 = QtWidgets.QLabel(self.expence_tracking)
        self.label_12.setGeometry(QtCore.QRect(30, 80, 71, 16))
        self.label_12.setStyleSheet("border:none;\n"
"font: 10pt \"Calibri\";")
        self.label_12.setObjectName("label_12")
        self.amount_expense = QtWidgets.QLineEdit(self.expence_tracking)
        self.amount_expense.setGeometry(QtCore.QRect(270, 100, 201, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(13)
        self.amount_expense.setFont(font)
        self.amount_expense.setObjectName("amount_expense")
        self.label_13 = QtWidgets.QLabel(self.expence_tracking)
        self.label_13.setGeometry(QtCore.QRect(280, 80, 71, 16))
        self.label_13.setStyleSheet("border:none;\n"
"font: 10pt \"Calibri\";")
        self.label_13.setObjectName("label_13")
        self.date_expence = QtWidgets.QDateEdit(self.expence_tracking)
        self.date_expence.setGeometry(QtCore.QRect(30, 170, 181, 31))
        self.date_expence.setStyleSheet("font: 10pt \"Calibri\";\n"
"padding:10px;\n"
"background:white;\n"
"color:black;")
        self.date_expence.setWrapping(False)
        self.date_expence.setButtonSymbols(QtWidgets.QAbstractSpinBox.UpDownArrows)
        self.date_expence.setDateTime(QtCore.QDateTime(QtCore.QDate(2024, 9, 14), QtCore.QTime(0, 0, 0)))
        self.date_expence.setMaximumDateTime(QtCore.QDateTime(QtCore.QDate(2024, 12, 31), QtCore.QTime(23, 59, 59)))
        self.date_expence.setMinimumDate(QtCore.QDate(2024, 9, 14))
        self.date_expence.setCalendarPopup(True)
        self.date_expence.setObjectName("date_expence")
        self.label_14 = QtWidgets.QLabel(self.expence_tracking)
        self.label_14.setGeometry(QtCore.QRect(40, 150, 71, 16))
        self.label_14.setStyleSheet("border:none;\n"
"font: 10pt \"Calibri\";")
        self.label_14.setObjectName("label_14")
        self.post_expence = QtWidgets.QPushButton(self.expence_tracking)
        self.post_expence.setGeometry(QtCore.QRect(40, 230, 111, 51))
        self.post_expence.setStyleSheet("QPushButton{\n"
"    background:rgb(85, 255, 0);\n"
"    color:rgb(47, 47, 47);\n"
"    border:0.1px solid;\n"
"    font: 87 10pt \"Arial Black\";\n"
"}\n"
"QPushButton:hover{\n"
"    background:rgb(150, 254, 94);\n"
"}")
        self.post_expence.setObjectName("post_expence")
        self.clear_expence = QtWidgets.QPushButton(self.expence_tracking)
        self.clear_expence.setGeometry(QtCore.QRect(350, 230, 111, 51))
        self.clear_expence.setStyleSheet("QPushButton{\n"
"    background:rgb(255, 170, 0);\n"
"    color:rgb(47, 47, 47);\n"
"    border:0.1px solid;\n"
"    font: 87 10pt \"Arial Black\";\n"
"}\n"
"QPushButton:hover{\n"
"    background:rgb(255, 205, 105);\n"
"}")
        self.clear_expence.setObjectName("clear_expence")
        self.label_20 = QtWidgets.QLabel(self.expence_tracking)
        self.label_20.setGeometry(QtCore.QRect(130, 50, 381, 16))
        self.label_20.setStyleSheet("border:none;\n"
"font: 10pt \"Calibri\";")
        self.label_20.setObjectName("label_20")
        self.next_income_2 = QtWidgets.QPushButton(self.expence_tracking)
        self.next_income_2.setGeometry(QtCore.QRect(350, 160, 111, 51))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(10)
        self.next_income_2.setFont(font)
        self.next_income_2.setStyleSheet("QPushButton{\n"
"    background:rgb(24, 64, 62);\n"
"    border:0.1px solid;\n"
"    font: 87 10pt \"Arial Black\";\n"
"}\n"
"QPushButton:hover{\n"
"    background:rgb(255,255,255);\n"
"}")
        self.next_income_2.setText("")
        self.next_income_2.setIcon(icon11)
        self.next_income_2.setIconSize(QtCore.QSize(20, 20))
        self.next_income_2.setObjectName("next_income_2")
        self.StackedWidget.addWidget(self.expence_tracking)
        self.budget_management = QtWidgets.QWidget()
        self.budget_management.setObjectName("budget_management")
        self.label_15 = QtWidgets.QLabel(self.budget_management)
        self.label_15.setGeometry(QtCore.QRect(140, 10, 201, 41))
        self.label_15.setStyleSheet("font: 75 14pt \"Calibri\";\n"
"padding:10px;")
        self.label_15.setScaledContents(True)
        self.label_15.setObjectName("label_15")
        self.label_16 = QtWidgets.QLabel(self.budget_management)
        self.label_16.setGeometry(QtCore.QRect(140, 50, 381, 21))
        self.label_16.setStyleSheet("border:none;\n"
"font: 10pt \"Calibri\";")
        self.label_16.setObjectName("label_16")
        self.category_budget = QtWidgets.QComboBox(self.budget_management)
        self.category_budget.setGeometry(QtCore.QRect(30, 100, 181, 31))
        self.category_budget.setStyleSheet("font: 10pt \"Calibri\";")
        self.category_budget.setObjectName("category_budget")
        self.category_budget.addItem("")
        self.category_budget.addItem("")
        self.category_budget.addItem("")
        self.category_budget.addItem("")
        self.category_budget.addItem("")
        self.category_budget.addItem("")
        self.category_budget.addItem("")
        self.category_budget.addItem("")
        self.label_17 = QtWidgets.QLabel(self.budget_management)
        self.label_17.setGeometry(QtCore.QRect(30, 80, 71, 16))
        self.label_17.setStyleSheet("border:none;\n"
"font: 10pt \"Calibri\";")
        self.label_17.setObjectName("label_17")
        self.amount_budget = QtWidgets.QLineEdit(self.budget_management)
        self.amount_budget.setGeometry(QtCore.QRect(260, 100, 201, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(13)
        self.amount_budget.setFont(font)
        self.amount_budget.setObjectName("amount_budget")
        self.label_18 = QtWidgets.QLabel(self.budget_management)
        self.label_18.setGeometry(QtCore.QRect(270, 80, 231, 16))
        self.label_18.setStyleSheet("border:none;\n"
"font: 10pt \"Calibri\";")
        self.label_18.setObjectName("label_18")
        self.post_budget = QtWidgets.QPushButton(self.budget_management)
        self.post_budget.setGeometry(QtCore.QRect(200, 160, 111, 51))
        self.post_budget.setStyleSheet("QPushButton{\n"
"    background:rgb(85, 255, 0);\n"
"    color:rgb(47, 47, 47);\n"
"    border:0.1px solid;\n"
"    font: 87 10pt \"Arial Black\";\n"
"}\n"
"QPushButton:hover{\n"
"    background:rgb(150, 254, 94);\n"
"}")
        self.post_budget.setObjectName("post_budget")
        self.clear_budget = QtWidgets.QPushButton(self.budget_management)
        self.clear_budget.setGeometry(QtCore.QRect(360, 160, 111, 51))
        self.clear_budget.setStyleSheet("QPushButton{\n"
"    background:rgb(255, 170, 0);\n"
"    color:rgb(47, 47, 47);\n"
"    border:0.1px solid;\n"
"    font: 87 10pt \"Arial Black\";\n"
"}\n"
"QPushButton:hover{\n"
"    background:rgb(255, 205, 105);\n"
"}")
        self.clear_budget.setObjectName("clear_budget")
        self.next_income_3 = QtWidgets.QPushButton(self.budget_management)
        self.next_income_3.setGeometry(QtCore.QRect(40, 160, 111, 51))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(10)
        self.next_income_3.setFont(font)
        self.next_income_3.setStyleSheet("QPushButton{\n"
"    background:rgb(24, 64, 62);\n"
"    border:0.1px solid;\n"
"    font: 87 10pt \"Arial Black\";\n"
"}\n"
"QPushButton:hover{\n"
"    background:rgb(255,255,255);\n"
"}")
        self.next_income_3.setText("")
        self.next_income_3.setIcon(icon11)
        self.next_income_3.setIconSize(QtCore.QSize(20, 20))
        self.next_income_3.setObjectName("next_income_3")
        self.StackedWidget.addWidget(self.budget_management)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 842, 18))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuNew = QtWidgets.QMenu(self.menuFile)
        self.menuNew.setIcon(icon6)
        self.menuNew.setObjectName("menuNew")
        self.menuOpen = QtWidgets.QMenu(self.menuFile)
        self.menuOpen.setIcon(icon7)
        self.menuOpen.setObjectName("menuOpen")
        self.menuSave = QtWidgets.QMenu(self.menuFile)
        self.menuSave.setIcon(icon8)
        self.menuSave.setObjectName("menuSave")
        self.menuAs_CSV = QtWidgets.QMenu(self.menuSave)
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap(":/icons_2/icons/File-Chart.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.menuAs_CSV.setIcon(icon12)
        self.menuAs_CSV.setObjectName("menuAs_CSV")
        self.menuAs_Excel = QtWidgets.QMenu(self.menuSave)
        icon13 = QtGui.QIcon()
        icon13.addPixmap(QtGui.QPixmap(":/icons_2/icons/File-Excel.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.menuAs_Excel.setIcon(icon13)
        self.menuAs_Excel.setObjectName("menuAs_Excel")
        self.menuImport = QtWidgets.QMenu(self.menuFile)
        icon14 = QtGui.QIcon()
        icon14.addPixmap(QtGui.QPixmap(":/icons/png_64/Download.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.menuImport.setIcon(icon14)
        self.menuImport.setObjectName("menuImport")
        self.menuEdit = QtWidgets.QMenu(self.menubar)
        icon15 = QtGui.QIcon()
        icon15.addPixmap(QtGui.QPixmap(":/icons/png_64/Settings.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.menuEdit.setIcon(icon15)
        self.menuEdit.setObjectName("menuEdit")
        self.menuMenu = QtWidgets.QMenu(self.menubar)
        icon16 = QtGui.QIcon()
        icon16.addPixmap(QtGui.QPixmap(":/icons/png_64/Menu.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.menuMenu.setIcon(icon16)
        self.menuMenu.setObjectName("menuMenu")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionSave_as = QtWidgets.QAction(MainWindow)
        icon17 = QtGui.QIcon()
        icon17.addPixmap(QtGui.QPixmap(":/icons/png_64/Ok.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSave_as.setIcon(icon17)
        self.actionSave_as.setObjectName("actionSave_as")
        self.actionQuit = QtWidgets.QAction(MainWindow)
        self.actionQuit.setIcon(icon5)
        self.actionQuit.setObjectName("actionQuit")
        self.actionUndo = QtWidgets.QAction(MainWindow)
        self.actionUndo.setEnabled(True)
        icon18 = QtGui.QIcon()
        icon18.addPixmap(QtGui.QPixmap(":/icons_2/icons/2x_reload.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionUndo.setIcon(icon18)
        self.actionUndo.setObjectName("actionUndo")
        self.actionClear = QtWidgets.QAction(MainWindow)
        self.actionClear.setObjectName("actionClear")
        self.actionPaste = QtWidgets.QAction(MainWindow)
        icon19 = QtGui.QIcon()
        icon19.addPixmap(QtGui.QPixmap(":/icons/png_64/File-Plus.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionPaste.setIcon(icon19)
        self.actionPaste.setObjectName("actionPaste")
        self.actionCopy = QtWidgets.QAction(MainWindow)
        icon20 = QtGui.QIcon()
        icon20.addPixmap(QtGui.QPixmap(":/icons/png_64/Copy.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionCopy.setIcon(icon20)
        self.actionCopy.setObjectName("actionCopy")
        self.actionRedo = QtWidgets.QAction(MainWindow)
        icon21 = QtGui.QIcon()
        icon21.addPixmap(QtGui.QPixmap(":/icons_2/icons/2x_anti-reload.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionRedo.setIcon(icon21)
        self.actionRedo.setObjectName("actionRedo")
        self.actionPreferences = QtWidgets.QAction(MainWindow)
        self.actionPreferences.setObjectName("actionPreferences")
        self.actionIncome_Tracking = QtWidgets.QAction(MainWindow)
        self.actionIncome_Tracking.setObjectName("actionIncome_Tracking")
        self.actionExpence_Tracking = QtWidgets.QAction(MainWindow)
        self.actionExpence_Tracking.setObjectName("actionExpence_Tracking")
        self.actionBudget_Tracking = QtWidgets.QAction(MainWindow)
        self.actionBudget_Tracking.setObjectName("actionBudget_Tracking")
        self.actionReports = QtWidgets.QAction(MainWindow)
        self.actionReports.setIcon(icon4)
        self.actionReports.setObjectName("actionReports")
        self.actionWebsite = QtWidgets.QAction(MainWindow)
        self.actionWebsite.setIcon(icon9)
        self.actionWebsite.setObjectName("actionWebsite")
        self.actionDocumentation = QtWidgets.QAction(MainWindow)
        icon22 = QtGui.QIcon()
        icon22.addPixmap(QtGui.QPixmap(":/icons_2/icons/File-Unlock.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionDocumentation.setIcon(icon22)
        self.actionDocumentation.setObjectName("actionDocumentation")
        self.actionExport = QtWidgets.QAction(MainWindow)
        self.actionExport.setObjectName("actionExport")
        self.actionIncome_Source = QtWidgets.QAction(MainWindow)
        self.actionIncome_Source.setObjectName("actionIncome_Source")
        self.actionExpence_Source = QtWidgets.QAction(MainWindow)
        self.actionExpence_Source.setObjectName("actionExpence_Source")
        self.actionBudget_Management = QtWidgets.QAction(MainWindow)
        self.actionBudget_Management.setObjectName("actionBudget_Management")
        self.actionIncome_Data = QtWidgets.QAction(MainWindow)
        self.actionIncome_Data.setObjectName("actionIncome_Data")
        self.actionExpence_Data = QtWidgets.QAction(MainWindow)
        self.actionExpence_Data.setObjectName("actionExpence_Data")
        self.actionBudget_Data = QtWidgets.QAction(MainWindow)
        self.actionBudget_Data.setObjectName("actionBudget_Data")
        self.actionIncome_Tracking_Data = QtWidgets.QAction(MainWindow)
        self.actionIncome_Tracking_Data.setObjectName("actionIncome_Tracking_Data")
        self.actionExpence_Tracking_Data = QtWidgets.QAction(MainWindow)
        self.actionExpence_Tracking_Data.setObjectName("actionExpence_Tracking_Data")
        self.actionBudget_Management_Data = QtWidgets.QAction(MainWindow)
        self.actionBudget_Management_Data.setObjectName("actionBudget_Management_Data")
        self.actionIncome_Tracking_Data_2 = QtWidgets.QAction(MainWindow)
        self.actionIncome_Tracking_Data_2.setObjectName("actionIncome_Tracking_Data_2")
        self.actionExpence_Tracking_Data_2 = QtWidgets.QAction(MainWindow)
        self.actionExpence_Tracking_Data_2.setObjectName("actionExpence_Tracking_Data_2")
        self.actionBudget_Management_Data_2 = QtWidgets.QAction(MainWindow)
        self.actionBudget_Management_Data_2.setObjectName("actionBudget_Management_Data_2")
        self.actionIncome_Tracking_Data_3 = QtWidgets.QAction(MainWindow)
        self.actionIncome_Tracking_Data_3.setObjectName("actionIncome_Tracking_Data_3")
        self.actionExpence_Tracking_Data_3 = QtWidgets.QAction(MainWindow)
        self.actionExpence_Tracking_Data_3.setObjectName("actionExpence_Tracking_Data_3")
        self.actionBudget_Management_Data_3 = QtWidgets.QAction(MainWindow)
        self.actionBudget_Management_Data_3.setObjectName("actionBudget_Management_Data_3")
        self.actionPrevious_Reports = QtWidgets.QAction(MainWindow)
        self.actionPrevious_Reports.setObjectName("actionPrevious_Reports")
        self.menuNew.addAction(self.actionIncome_Source)
        self.menuNew.addAction(self.actionExpence_Source)
        self.menuNew.addAction(self.actionBudget_Management)
        self.menuOpen.addAction(self.actionIncome_Data)
        self.menuOpen.addAction(self.actionExpence_Data)
        self.menuOpen.addAction(self.actionBudget_Data)
        self.menuAs_CSV.addAction(self.actionIncome_Tracking_Data)
        self.menuAs_CSV.addAction(self.actionExpence_Tracking_Data)
        self.menuAs_CSV.addAction(self.actionBudget_Management_Data)
        self.menuAs_Excel.addAction(self.actionIncome_Tracking_Data_2)
        self.menuAs_Excel.addAction(self.actionExpence_Tracking_Data_2)
        self.menuAs_Excel.addAction(self.actionBudget_Management_Data_2)
        self.menuSave.addAction(self.menuAs_CSV.menuAction())
        self.menuSave.addAction(self.menuAs_Excel.menuAction())
        self.menuImport.addAction(self.actionIncome_Tracking_Data_3)
        self.menuImport.addAction(self.actionExpence_Tracking_Data_3)
        self.menuImport.addAction(self.actionBudget_Management_Data_3)
        self.menuImport.addSeparator()
        self.menuImport.addAction(self.actionPrevious_Reports)
        self.menuFile.addAction(self.menuNew.menuAction())
        self.menuFile.addAction(self.menuOpen.menuAction())
        self.menuFile.addAction(self.menuSave.menuAction())
        self.menuFile.addAction(self.menuImport.menuAction())
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionQuit)
        self.menuEdit.addAction(self.actionUndo)
        self.menuEdit.addAction(self.actionRedo)
        self.menuEdit.addAction(self.actionClear)
        self.menuEdit.addAction(self.actionPaste)
        self.menuEdit.addAction(self.actionCopy)
        self.menuEdit.addAction(self.actionPreferences)
        self.menuMenu.addAction(self.actionIncome_Tracking)
        self.menuMenu.addAction(self.actionExpence_Tracking)
        self.menuMenu.addAction(self.actionBudget_Tracking)
        self.menuMenu.addAction(self.actionReports)
        self.menuHelp.addAction(self.actionWebsite)
        self.menuHelp.addAction(self.actionDocumentation)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())
        self.menubar.addAction(self.menuMenu.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        self.StackedWidget.setCurrentIndex(3)
        self.quit_btn.clicked.connect(MainWindow.close) # type: ignore
        self.actionQuit.triggered.connect(MainWindow.close) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Income Tracker"))
        self.label_3.setText(_translate("MainWindow", "Menu"))
        self.income_tracking_btn.setText(_translate("MainWindow", "Income Tracking"))
        self.expence_tracking_btn.setText(_translate("MainWindow", "Expense tracking"))
        self.budget_management_btn.setText(_translate("MainWindow", "Budget Management"))
        self.reports_btn.setText(_translate("MainWindow", "Reports"))
        self.quit_btn.setText(_translate("MainWindow", "Quit"))
        self.label_5.setText(_translate("MainWindow", "Personal Finance Tracker - Onesmusbett co."))
        self.label_19.setText(_translate("MainWindow", "Welcome"))
        self.textBrowser.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Calibri\'; font-size:11pt;\">Welcome to your personal finance tracker software. Developed by onesmus bett, this is the best tool for tracking and managing your wallet.  The User interface is simple to use and should come with ease how to make your way around the application. </span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'Calibri\'; font-size:11pt;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Calibri\'; font-size:11pt;\">Thank you for using our software.</span></p></body></html>"))
        self.label_6.setText(_translate("MainWindow", "Income source"))
        self.label_7.setText(_translate("MainWindow", "Amount"))
        self.label_8.setText(_translate("MainWindow", "Date"))
        self.post_income.setText(_translate("MainWindow", "Post"))
        self.clear_income.setText(_translate("MainWindow", "Clear"))
        self.label_10.setText(_translate("MainWindow", "Income Tracking"))
        self.label_21.setText(_translate("MainWindow", "Enter your source of income e.g Salary, side-hustle, etc"))
        self.label_11.setText(_translate("MainWindow", "Expense Tracking"))
        self.rent_expence.setItemText(0, _translate("MainWindow", "Rent"))
        self.rent_expence.setItemText(1, _translate("MainWindow", "Groceries"))
        self.rent_expence.setItemText(2, _translate("MainWindow", "Shopping"))
        self.rent_expence.setItemText(3, _translate("MainWindow", "Electric Bill"))
        self.rent_expence.setItemText(4, _translate("MainWindow", "Water Bill"))
        self.rent_expence.setItemText(5, _translate("MainWindow", "School Fees"))
        self.rent_expence.setItemText(6, _translate("MainWindow", "Leisure"))
        self.rent_expence.setItemText(7, _translate("MainWindow", "other"))
        self.label_12.setText(_translate("MainWindow", "Category"))
        self.label_13.setText(_translate("MainWindow", "Amount"))
        self.label_14.setText(_translate("MainWindow", "Date"))
        self.post_expence.setText(_translate("MainWindow", "Post"))
        self.clear_expence.setText(_translate("MainWindow", "Clear"))
        self.label_20.setText(_translate("MainWindow", "Enter expences that you have had for each category"))
        self.label_15.setText(_translate("MainWindow", "Budget Management"))
        self.label_16.setText(_translate("MainWindow", "Enter Budget amount for different categories"))
        self.category_budget.setItemText(0, _translate("MainWindow", "Rent"))
        self.category_budget.setItemText(1, _translate("MainWindow", "Groceries"))
        self.category_budget.setItemText(2, _translate("MainWindow", "Shopping"))
        self.category_budget.setItemText(3, _translate("MainWindow", "Electric Bill"))
        self.category_budget.setItemText(4, _translate("MainWindow", "Water Bill"))
        self.category_budget.setItemText(5, _translate("MainWindow", "School Fees"))
        self.category_budget.setItemText(6, _translate("MainWindow", "Leisure"))
        self.category_budget.setItemText(7, _translate("MainWindow", "other"))
        self.label_17.setText(_translate("MainWindow", "Category"))
        self.label_18.setText(_translate("MainWindow", "Budget Amount"))
        self.post_budget.setText(_translate("MainWindow", "Done"))
        self.clear_budget.setText(_translate("MainWindow", "Clear"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuNew.setTitle(_translate("MainWindow", "New"))
        self.menuOpen.setTitle(_translate("MainWindow", "Open"))
        self.menuSave.setTitle(_translate("MainWindow", "Save"))
        self.menuAs_CSV.setTitle(_translate("MainWindow", "As CSV"))
        self.menuAs_Excel.setTitle(_translate("MainWindow", "As Excel"))
        self.menuImport.setTitle(_translate("MainWindow", "Import"))
        self.menuEdit.setTitle(_translate("MainWindow", "Edit"))
        self.menuMenu.setTitle(_translate("MainWindow", "Menu"))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))
        self.actionSave_as.setText(_translate("MainWindow", "Save as..."))
        self.actionQuit.setText(_translate("MainWindow", "Quit"))
        self.actionUndo.setText(_translate("MainWindow", "Undo"))
        self.actionUndo.setShortcut(_translate("MainWindow", "Ctrl+Z"))
        self.actionClear.setText(_translate("MainWindow", "Clear"))
        self.actionClear.setShortcut(_translate("MainWindow", "Ctrl+X"))
        self.actionPaste.setText(_translate("MainWindow", "Paste"))
        self.actionPaste.setShortcut(_translate("MainWindow", "Ctrl+V"))
        self.actionCopy.setText(_translate("MainWindow", "Copy"))
        self.actionCopy.setShortcut(_translate("MainWindow", "Ctrl+C"))
        self.actionRedo.setText(_translate("MainWindow", "Redo"))
        self.actionRedo.setShortcut(_translate("MainWindow", "Ctrl+Shift+Z"))
        self.actionPreferences.setText(_translate("MainWindow", "Preferences"))
        self.actionIncome_Tracking.setText(_translate("MainWindow", "Income Tracking"))
        self.actionExpence_Tracking.setText(_translate("MainWindow", "Expence Tracking"))
        self.actionBudget_Tracking.setText(_translate("MainWindow", "Budget Tracking"))
        self.actionReports.setText(_translate("MainWindow", "Reports"))
        self.actionWebsite.setText(_translate("MainWindow", "About"))
        self.actionDocumentation.setText(_translate("MainWindow", "Documentation"))
        self.actionExport.setText(_translate("MainWindow", "Export"))
        self.actionIncome_Source.setText(_translate("MainWindow", "Income Source"))
        self.actionExpence_Source.setText(_translate("MainWindow", "Expence Source"))
        self.actionBudget_Management.setText(_translate("MainWindow", "Budget Management"))
        self.actionIncome_Data.setText(_translate("MainWindow", "Income Data"))
        self.actionExpence_Data.setText(_translate("MainWindow", "Expence Data"))
        self.actionBudget_Data.setText(_translate("MainWindow", "Budget Data"))
        self.actionIncome_Tracking_Data.setText(_translate("MainWindow", "Income Tracking Data"))
        self.actionExpence_Tracking_Data.setText(_translate("MainWindow", "Expence Tracking Data"))
        self.actionBudget_Management_Data.setText(_translate("MainWindow", "Budget Management Data"))
        self.actionIncome_Tracking_Data_2.setText(_translate("MainWindow", "Income Tracking Data"))
        self.actionExpence_Tracking_Data_2.setText(_translate("MainWindow", "Expence Tracking Data"))
        self.actionBudget_Management_Data_2.setText(_translate("MainWindow", "Budget Management Data"))
        self.actionIncome_Tracking_Data_3.setText(_translate("MainWindow", "Income Tracking Data"))
        self.actionExpence_Tracking_Data_3.setText(_translate("MainWindow", "Expence Tracking Data"))
        self.actionBudget_Management_Data_3.setText(_translate("MainWindow", "Budget Management Data"))
        self.actionPrevious_Reports.setText(_translate("MainWindow", "Previous Reports"))
import resources_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
